image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""

stages:          # List of stages for jobs, and their order of execution
  - test-and-deploy

deploy-job:
  stage: test-and-deploy
  only:
    - main
  before_script:
    - 'which ssh-agent || (apk update && apk add openssh-client)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $PROD_SERVER_PORT $PROD_SERVER_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - docker build -t itnun-back .
    - ssh $PROD_SERVER_USER@$PROD_SERVER_HOST -p $PROD_SERVER_PORT "cd ~/docker-compose/itnun-back-nest && git pull gitlab main && sudo doppler run --token='$DOPPLER_TOKEN' -- docker compose -f docker-compose-prod.yml up -d --build"

  when: manual

