version: "3.8"

networks:
  main_net:
    name: main_main_net
    external: true
  back_net:
    driver: bridge

services:
  itnun-back:
    build: ./
    container_name: itnun-back
    image: itnun-back
    expose:
      - ${WAS_PORT}
    volumes:
      - ./itnun-log:/log
    environment:
      - DOPPLER_TOKEN
    restart: always
    depends_on:
      - mariadb
    networks:
      - main_net
      - back_net
  mariadb:
    container_name: ${MYSQL_HOSTNAME}
    image: mariadb:10.11.2
    expose:
      - ${MYSQL_PORT}
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ
    restart: always
    networks:
      - back_net